spring.application.name=photogenic
spring.data.mongodb.database=photogenicDB
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://username&password.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

